### ISSUE TITLE
USER STORY: <Publish A Poll>

### ISSUE THREAD

**Issue by alanpaterson82** [alanpaterson82/My-First-Agile-Project#4]
_In order_ to collect users feedback, _as an_ administrator, _I can_ publish a poll

**Comment by alanpaterson82** [comment]
## Acceptance Criteria ##

* Feedback includes ease of navigation, comments on the layout and 'other'
* The administraotr can choose the font for the poll
* The published poll should be on the homepage

## Tasks ##

- [ ] Create sections for each feedback area
- [ ] Choose the most user friendly font
- [ ] Add the poll questions to the homepage
